# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curly < Formula
  desc "curly tool"
  homepage "https://github.com/bilal-bhatti/curly"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bilal-bhatti/curly/releases/download/v0.0.4/curly_0.0.4_Darwin_arm64.tar.gz"
      sha256 "6b86a07d47a55354e7bce1ff2acf691d7774df62b0f273151cdc714c17b08a80"

      def install
        bin.install "curly"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/curly/releases/download/v0.0.4/curly_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "8452e215e9745934fe9e0eeefe31a9e183897da6a6f7dfb27dcd65bbd99a2912"

      def install
        bin.install "curly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bilal-bhatti/curly/releases/download/v0.0.4/curly_0.0.4_Linux_arm64.tar.gz"
      sha256 "7cbf9cf4a545d58fffb588c3e4c36d598e0abb8fd73126b249e068e4548f4662"

      def install
        bin.install "curly"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/curly/releases/download/v0.0.4/curly_0.0.4_Linux_x86_64.tar.gz"
      sha256 "d8251d170a2e924bebd688cb9adc2406a7d169ea91d57da5503720d99beac522"

      def install
        bin.install "curly"
      end
    end
  end
end
