# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc ""
  homepage ""
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.6/jt_0.1.6_Darwin_arm64.tar.gz"
      sha256 "e79c151349f8f2c29a24ac32a65965d9eeddd82a21b9ac95b1a4edf25f7cf9e9"

      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.6/jt_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "db7486a3755994c98676de7b7b81656037ab9972a77106598cad63dca71e45bc"

      def install
        bin.install "jt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.6/jt_0.1.6_Linux_arm64.tar.gz"
      sha256 "2bd6c73a6cf2de2b5a49afb3e825d182f91366185777361bf7a934b93337abe3"

      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.6/jt_0.1.6_Linux_x86_64.tar.gz"
      sha256 "d4cf57deba951815048307775d3ff99154585c8c4f0b55a2c45232d3e3a29884"

      def install
        bin.install "jt"
      end
    end
  end
end
