# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.2/jt_0.1.2_Darwin_arm64.tar.gz"
      sha256 "d28893c9f42451cb8663831be51ca0eb0f46c688f136f71d6804d219d4a30b2a"

      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.2/jt_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "9f9dee889d0c3cf573e3cc4a95bd740360bb649334e87cabc85571af8041af61"

      def install
        bin.install "jt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.2/jt_0.1.2_Linux_arm64.tar.gz"
      sha256 "a731521f64188c711d880efbc5daaa3efbf6e325bb85bacbd20edc1bdd68d094"

      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/jt/releases/download/v0.1.2/jt_0.1.2_Linux_x86_64.tar.gz"
      sha256 "5a46c3088ce54dad63bbe48b5606112b14654eeb105b167c6d518b4ea33868eb"

      def install
        bin.install "jt"
      end
    end
  end
end
