# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipline < Formula
  desc ""
  homepage ""
  version "0.4.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.2/zipline_Darwin_arm64.tar.gz"
      sha256 "9c35e22c5cf1492b0af195f13c0ca5dc8b50cd438de5065094aca00e19cc7180"

      def install
        bin.install "zipline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.2/zipline_Darwin_x86_64.tar.gz"
      sha256 "2253e6d3646904111a7b6e6c9bda69711f4e26fdf0b6d04b8db74174ab83481e"

      def install
        bin.install "zipline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.2/zipline_Linux_arm64.tar.gz"
      sha256 "f3a37a64baaa2d7cacd28e20bf93a4db00d14712228be5d0ab748ddeff0776ff"

      def install
        bin.install "zipline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.2/zipline_Linux_x86_64.tar.gz"
      sha256 "0fb9b940220962cd1574256c8636acbb23bd83bd42905d82868f5d90168565ea"

      def install
        bin.install "zipline"
      end
    end
  end
end
