# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipline < Formula
  desc ""
  homepage ""
  version "0.4.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.4/zipline_Darwin_arm64.tar.gz"
      sha256 "ab582ff0f6c3ea7fee19d982fcb68b803784a4030f82db4f156c664a12f2e84c"

      def install
        bin.install "zipline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.4/zipline_Darwin_x86_64.tar.gz"
      sha256 "0df765df69a93252ff3a98db8fed66fecf3d3ea8b452064fdc07b615daaad97b"

      def install
        bin.install "zipline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.4/zipline_Linux_arm64.tar.gz"
      sha256 "644cf85300b0a294a60575519439ee38a6567efe351ce1e587ca7de1e4705a10"

      def install
        bin.install "zipline"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bilal-bhatti/zipline/releases/download/v0.4.4/zipline_Linux_x86_64.tar.gz"
      sha256 "7b503d059a12083c9340109e42fbfcf27f418588b06207f4e17f63752315c423"

      def install
        bin.install "zipline"
      end
    end
  end
end
