# This file was generated by GoReleaser. DO NOT EDIT.
cask "zipline" do
  name "zipline"
  desc ""
  homepage ""
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zipline"

  on_macos do
    on_intel do
      url "https://github.com/bilal-bhatti/zipline/releases/download/v#{version}/zipline_Darwin_x86_64.tar.gz"
      sha256 "3e2d920ac72947fb7b3b048bd46a6f44f4d61b75ee419e5f7875869a6784d507"
    end
    on_arm do
      url "https://github.com/bilal-bhatti/zipline/releases/download/v#{version}/zipline_Darwin_arm64.tar.gz"
      sha256 "d5addb7e416e760346873aa1fef4f935d810954375b59e3c9dad4e502bd33090"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bilal-bhatti/zipline/releases/download/v#{version}/zipline_Linux_x86_64.tar.gz"
      sha256 "c4fd2c75c52e8f83981c7bfc87a0e73e299b9732c5ff9b4ea112b187f5e3c765"
    end
    on_arm do
      url "https://github.com/bilal-bhatti/zipline/releases/download/v#{version}/zipline_Linux_arm64.tar.gz"
      sha256 "57adac5fbcc1004427b226018c0d6f6fd5717319047bdbd344276e32f130f235"
    end
  end

  # No zap stanza required
end
